### ISSUE TITLE
[BUG] <title>Unable to paste into machine settings

### ISSUE THREAD

**Issue by edfield** [linuxserver/docker-cura#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

New Cura install, trying to copy my current startup setting into machine settings. Can't paste anything into machine settings.  Can manually type the gcode in, but it would be much easier if I could paste in my current settings.

### Expected Behavior

Would expect copy and paste to work. 

### Steps To Reproduce

Default install, start cure go to settings, printers, select printer, machine settings

### Environment

```markdown
- OS: unraid 6.2.10
- How docker service was installed: unraid app store, accepted all defaults on template
```

### CPU architecture

x86-64

### Docker creation

```bash
unraid GUI, accepted all defaults.
```

### Container logs

```bash
Not sure where the logs are stored in unraid.
```

**Comment by rickyphewitt** [comment]
I ran into this issue as well. Right clicking inside the start/end gcode printer settings did not open up a menu. I was able to use they keyboard shortcut ctr+v to paste the gcode. 

I did have to add the gcode to the KASM clipboard first.

**Comment by j0nnymoe** [comment]
Correct way is to use the kasm clipboard or make sure the container is behind a reverse proxy with a valid SSL certificate to allow seamless clipboard.
