### ISSUE TITLE
[BUG] <title>linuxserver/cura will not slice</title>

### ISSUE THREAD

**Issue by nathanielstenzel** [linuxserver/docker-cura#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It complains about an unknown error a little after you attempt to slice an stl file.

### Expected Behavior

I would hope it would at least give more information about why the failure occurred.  What I would really like is success but I do not know if everything is configured right.

### Steps To Reproduce

**1.**

System:
  Kernel: 6.8.0-45-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0 clocksource: tsc
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Openbox vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Machine:
  Type: Desktop System: Dell product: OptiPlex 7010 v: 01 serial: <superuser required> Chassis:
    type: 3 serial: <superuser required>
  Mobo: Dell model: 0YXT71 v: A01 serial: <superuser required> part-nu: OptiPlex 7010
    uuid: <superuser required> UEFI: Dell v: A29 date: 06/28/2018
CPU:
  Info: quad core model: Intel Core i5-3470 bits: 64 type: MCP smt: <unsupported> arch: Ivy Bridge
    rev: 9 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3392 min/max: 1600/3600 cores: 1: 3392 2: 3392 3: 3392 4: 3392
    bogomips: 25540
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics vendor: Dell driver: i915
    v: kernel arch: Gen-7 ports: active: HDMI-A-1 empty: DP-1, DP-2, HDMI-A-2, VGA-1 bus-ID: 00:02.0
    chip-ID: 8086:0152 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: crocus gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.00x11.22") s-diag: 582mm (22.93")
  Monitor-1: HDMI-A-1 mapped: HDMI-1 model: Samsung serial: <filter> res: 1920x1080 hz: 60
    dpi: 305 size: 160x90mm (6.3x3.54") diag: 1021mm (40.2") modes: max: 1920x1080 min: 720x400
  API: EGL v: 1.5 hw: drv: intel crocus platforms: device: 0 drv: crocus device: 1 drv: swrast
    surfaceless: drv: crocus x11: drv: crocus inactive: gbm,wayland
  API: OpenGL v: 4.5 compat-v: 4.2 vendor: intel mesa v: 24.0.9-0ubuntu0.1 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel HD Graphics 2500 (IVB GT1) device-ID: 8086:0152
  API: Vulkan v: 1.3.275 layers: 8 surfaces: xcb,xlib device: 0 type: integrated-gpu driver: N/A
    device-ID: 8086:0152 device: 1 type: cpu driver: N/A device-ID: 10005:0000
Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Dell 7 driver: snd_hda_intel
    v: kernel bus-ID: 00:1b.0 chip-ID: 8086:1e20 class-ID: 0403
  API: ALSA v: k6.8.0-45-generic status: kernel-api with: osspd status: active
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e v: kernel port: f080
    bus-ID: 00:19.0 chip-ID: 8086:1502 class-ID: 0200
  IF: eno1 state: down mac: <filter>
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie: speed: 5 GT/s lanes: 1
    bus-ID: 02:00.0 chip-ID: 8086:2723 class-ID: 0280
  IF: wlp2s0 state: up mac: <filter>
  IF-ID-1: docker0 state: up speed: 10000 Mbps duplex: unknown mac: <filter>
  IF-ID-2: lxcbr0 state: down mac: <filter>
  IF-ID-3: vethf1ef2ca state: up speed: 10000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth driver: btusb v: 0.8 type: USB rev: 2.0 speed: 12 Mb/s lanes: 1
    bus-ID: 1-1.5:5 chip-ID: 8087:0029 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 763.85 GiB used: 618.66 GiB (81.0%)
  ID-1: /dev/sda vendor: Western Digital model: WD3200BEVT-60ZCT0 size: 298.09 GiB
    speed: 3.0 Gb/s tech: HDD rpm: 5400 serial: <filter> fw-rev: 1A11 scheme: MBR
  ID-2: /dev/sdb vendor: Western Digital model: WDBNCE5000PNC size: 465.76 GiB speed: 3.0 Gb/s
    tech: SSD serial: <filter> fw-rev: 20RL scheme: GPT
Partition:
  ID-1: / size: 356.79 GiB used: 335.94 GiB (94.2%) fs: ext4 dev: /dev/sdb5
  ID-2: /boot/efi size: 96 MiB used: 31.1 MiB (32.4%) fs: vfat dev: /dev/sdb2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 1.82 GiB (91.2%) priority: -2 file: /oldhome/swapfile
USB:
  Hub-1: 1-0:1 info: full speed or root hub ports: 3 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-2: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 speed: 480 Mb/s
    lanes: 1 chip-ID: 8087:0024 class-ID: 0900
  Device-1: 1-1.3:3 info: Dell MS116 Optical Mouse type: mouse driver: hid-generic,usbhid
    interfaces: 1 rev: 2.0 speed: 1.5 Mb/s lanes: 1 power: 100mA chip-ID: 413c:301a class-ID: 0301
  Device-2: 1-1.5:5 info: Intel AX200 Bluetooth type: bluetooth driver: btusb interfaces: 2
    rev: 2.0 speed: 12 Mb/s lanes: 1 power: 100mA chip-ID: 8087:0029 class-ID: e001
  Hub-3: 2-0:1 info: full speed or root hub ports: 3 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-4: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 8 rev: 2.0 speed: 480 Mb/s
    lanes: 1 chip-ID: 8087:0024 class-ID: 0900
  Device-1: 2-1.6:3 info: HP DeskJet 2620 All-in-One Printer type: printer driver: usbfs
    interfaces: 4 rev: 2.0 speed: 480 Mb/s lanes: 1 power: 2mA chip-ID: 03f0:0053 class-ID: 0701
    serial: <filter>
  Hub-5: 3-0:1 info: hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 3-1:2 info: Dell KB216 Wired Keyboard type: keyboard,HID driver: hid-generic,usbhid
    interfaces: 2 rev: 1.1 speed: 1.5 Mb/s lanes: 1 power: 100mA chip-ID: 413c:2113 class-ID: 0300
  Device-2: 3-2:3 info: Saitek PLC P880 Pad type: HID driver: hid-generic,usbhid interfaces: 1
    rev: 1.1 speed: 1.5 Mb/s lanes: 1 power: 100mA chip-ID: 06a3:0109 class-ID: 0300
  Device-3: 3-3:4 info: Logitech Unifying Receiver type: keyboard,mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 98mA
    chip-ID: 046d:c52b class-ID: 0300
  Hub-6: 4-0:1 info: super-speed hub ports: 4 rev: 3.0 speed: 5 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 78.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  Packages: 4854 pm: dpkg pkgs: 4837 pm: flatpak pkgs: 17
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list
    1: deb [arch=amd64] http: //dl.google.com/linux/earth/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com wilma main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu noble main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/yannubuntu-boot-repair-noble.list
    1: deb [signed-by=/etc/apt/keyrings/yannubuntu-boot-repair-noble.gpg] https: //ppa.launchpadcontent.net/yannubuntu/boot-repair/ubuntu noble main
Info:
  Memory: total: 16 GiB note: est. available: 15.54 GiB used: 10.74 GiB (69.1%)
  Processes: 387 Power: uptime: 2d 21h 39m states: freeze,mem suspend: deep wakeups: 0
    hibernate: disabled Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.2.0 alt: 7/8/9/11/12 Client: Cinnamon v: 6.2.9 inxi: 3.3.34

**2 and 3.**
sudo docker run -d \
--name=cura \
--security-opt seccomp=unconfined `#optional` \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Etc/UTC \
-e NO_DECOR=1 \
-e DRINODE=/dev/dri/renderD128 \
-e VNC_RESOLUTION="800x600" \
-p 3000:3000 \
-p 3001:3001 \
-v /home/nathaniel/.local/share/cura/5.8/:/config \
--restart unless-stopped \
--device /dev/dri/renderD128 \
linuxserver/cura:latest

**4.**
Something along the lines of "Oops! We encountered an unexpected error during the slicing process..." but with no real details. It gives an option of giving a bug report to the Cura project. 

### Environment

```markdown
- OS:
Linux Mint 22 Wilma base: Ubuntu 24.04 noble
- How docker service was installed:
sudo apt install docker.io
sudo docker pull linuxserver/cura:latest
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker run -d \
--name=cura \
--security-opt seccomp=unconfined `#optional` \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Etc/UTC \
-e NO_DECOR=1 \
-e DRINODE=/dev/dri/renderD128 \
-e VNC_RESOLUTION="800x600" \
-p 3000:3000 \
-p 3001:3001 \
-v /home/nathaniel/.local/share/cura/5.8/:/config \
--restart unless-stopped \
--device /dev/dri/renderD128 \
linuxserver/cura:latest
```

### Container logs

```bash
nathaniel@nathaniel-OptiPlex-7010:~$ sudo docker logs -f cura
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
....+........+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.................+...+.+..................+..+.............+...+..+.+..+.......+..+...+.......+...+...+.....+....+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+........+......+..........+.........+......+......+.....+....+......+......+...+..+...+....+......+.....+.+......+.....+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.+...+..+...+.............+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+......+...+..+....+.....+...+.......+......+...+..+...+.+...............+......+...+........................+.....+.+......+...+...............+..+..................+.+.....+.......+...............+...+.....................+.....+....+.....+.+...+.....+...+.........+.+...+......+.....+......+.......+...+.....+.......+...+........+......+.+...+..+....+...................................+...+......+.+......+..+............+.+..+...+......................+..+.+...+..+....+...+..+......+.......+........+.............+......+.....+....+..+.........+.+..+...+.........+....+.....+................+.....+.............+...+..................+.....+.......+............+...+.....+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
**** creating video group videouk3h with id 137 ****
**** adding /dev/dri/renderD128 to video group videouk3h with id 137 ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Sep 21 2024 19:00:48
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
17

(UltiMaker-Cura:335): dbind-WARNING **: 17:50:34.084: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
xvnc_get_formats
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///opt/cura/share/cura/resources/qml/Actions.qml" and "file:///opt/cura/share/cura/resources/qml/Actions.qml"
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
 2024-09-29 17:52:31,698 [INFO] websocket 0: got client connection from 127.0.0.1
 2024-09-29 17:52:31,717 [PRIO] Connections: accepted: @192.168.12.145_1727632351.700892::websocket
xvnc_get_formats
xvnc_get_formats
[GFX1-]: glxtest: Cannot find DRM device
[GFX1-]: vaapitest: ERROR
[GFX1-]: vaapitest: VA-API test failed: failed to initialise VAAPI connection.

ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
xvnc_get_formats
ATTENTION: default value of option mesa_glthread overridden by environment.
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
 2024-09-29 17:55:28,125 [PRIO] Connections: closed: @192.168.12.145_1727632351.700892::websocket (Clean disconnection)
 2024-09-29 17:55:46,472 [INFO] websocket 1: got client connection from 127.0.0.1
 2024-09-29 17:55:46,492 [PRIO] Connections: accepted: @192.168.12.145_1727632546.472560::websocket
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
 2024-09-29 18:29:28,048 [PRIO] Connections: closed: @192.168.12.145_1727632546.472560::websocket (Clean disconnection)
 2024-09-29 18:33:51,518 [INFO] websocket 2: got client connection from 127.0.0.1
 2024-09-29 18:33:51,533 [PRIO] Connections: accepted: @192.168.12.145_1727634831.519229::websocket
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
[GFX1-]: glxtest: Cannot find DRM device
[GFX1-]: vaapitest: ERROR
[GFX1-]: vaapitest: VA-API test failed: failed to initialise VAAPI connection.

ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
xvnc_get_formats
ATTENTION: default value of option mesa_glthread overridden by environment.
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
 2024-09-29 18:47:37,565 [PRIO] Connections: closed: @192.168.12.145_1727634831.519229::websocket (Clean disconnection)
 2024-09-29 18:47:48,295 [INFO] websocket 3: got client connection from 127.0.0.1
 2024-09-29 18:47:48,309 [PRIO] Connections: accepted: @192.168.12.145_1727635668.296323::websocket
 2024-09-29 18:48:08,806 [PRIO] Connections: closed: @192.168.12.145_1727635668.296323::websocket (Clean disconnection)
 2024-09-29 18:48:09,247 [INFO] websocket 4: got client connection from 127.0.0.1
 2024-09-29 18:48:09,258 [PRIO] Connections: accepted: @192.168.12.145_1727635689.247996::websocket
 2024-09-29 18:50:59,749 [PRIO] Connections: closed: @192.168.12.145_1727635689.247996::websocket (Clean disconnection)
 2024-09-29 18:51:00,706 [INFO] websocket 5: got client connection from 127.0.0.1
 2024-09-29 18:51:00,716 [PRIO] Connections: accepted: @192.168.12.145_1727635860.706623::websocket
 2024-09-29 18:54:30,021 [PRIO] Connections: closed: @192.168.12.145_1727635860.706623::websocket (Clean disconnection)
 2024-09-29 18:54:36,278 [INFO] websocket 6: got client connection from 127.0.0.1
 2024-09-29 18:54:36,290 [PRIO] Connections: accepted: @192.168.12.145_1727636076.278744::websocket
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
[GFX1-]: glxtest: Cannot find DRM device
[GFX1-]: vaapitest: ERROR
[GFX1-]: vaapitest: VA-API test failed: failed to initialise VAAPI connection.

ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
xvnc_get_formats
ATTENTION: default value of option mesa_glthread overridden by environment.
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
xvnc_get_formats
```

**Comment by nathanielstenzel** [comment]
I do not know if this problem is from bad configuration, Cura issues or the linuxserver/cura docker app. Could someone confirm that this latest build of the docker app still works for them and then maybe we could compare notes and figure things out from there? 

Honestly, Ultimaker seriously needs to adjust how they make their interface layer.  The window size is also an issue...at least from a phone...I need to try on a tablet or better too. I did try on the computer itself, but that does not really count.

**Comment by nathanielstenzel** [comment]
Is anyone watching this project?

**Comment by j0nnymoe** [comment]
Could you provide a link to an stl you've tried so that we can try to replicate?

**Comment by j0nnymoe** [comment]
Though I've just noticed you've done this for your volume: `-v /home/nathaniel/.local/share/cura/5.8/:/config ` - are you trying to use an existing config?

**Comment by nathanielstenzel** [comment]
Is there something wrong with using a config file? Am I doing it wrong?
