### ISSUE TITLE
[FEAT] hepm chart

### ISSUE THREAD

**Issue by claywd** [linuxserver/docker-cura#13]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

a helm chart for running in k8s would be awesome.

### Reason for change

docker is.... being replaced essentially by something universially more robust and proven called kubernetes

### Proposed code change

some yaml

**Comment by j0nnymoe** [comment]
Docker isn't "essentially being replaced" at all. We don't have any plans to add helm charts.
